<#
.SYNOPSIS
  将 resources/ 目录中的二进制文件嵌入为 C 字节数组.
  生成 resources_embed.c, 供 CMake 编译到 exe 中.

.DESCRIPTION
  扫描 $ResourcesDir 下的所有文件, 为每个文件生成一个
  `static const uint8_t[]` 数组和一个 `resource_entry_t`
  表项. 输出文件覆盖 win_port/resource_embed.c 中的空表.

  Usage: powershell -File gen_resources.ps1 -ResourcesDir "resources" -OutputC "build/resources_embed.c"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ResourcesDir,

    [Parameter(Mandatory=$true)]
    [string]$OutputC
)

$ErrorActionPreference = "Stop"

# 确保输出目录存在
$outDir = Split-Path $OutputC -Parent
if ($outDir -and !(Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

# 收集资源文件
$files = Get-ChildItem -Path $ResourcesDir -File -Recurse -ErrorAction SilentlyContinue |
         Sort-Object FullName

# 开始写入
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("/* Auto-generated by gen_resources.ps1 — DO NOT EDIT */")
[void]$sb.AppendLine("/* Resources embedded from: $ResourcesDir */")
[void]$sb.AppendLine("")
[void]$sb.AppendLine('#include "resource_embed.h"')
[void]$sb.AppendLine("#include <stddef.h>")
[void]$sb.AppendLine("")

$entries = @()

foreach ($f in $files) {
    $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
    $name = $f.Name
    $size = $bytes.Length

    # 生成合法 C 标识符
    $arrName = "res_" + ($name -replace '[.\-/\\ ]', '_')

    # 相对路径 (用于 VFS)
    $relPath = $f.FullName.Substring($ResourcesDir.Length).TrimStart('\', '/') -replace '\\', '/'

    Write-Host "  Embedding: $relPath ($size bytes)"

    # 写入数组定义
    [void]$sb.AppendLine("/* $relPath — $size bytes */")
    [void]$sb.Append("static const uint8_t ${arrName}[] = {`n  ")

    $lineLen = 0
    for ($i = 0; $i -lt $size; $i++) {
        [void]$sb.AppendFormat("0x{0:X2},", $bytes[$i])
        $lineLen++
        if ($lineLen -ge 16) {
            [void]$sb.Append("`n  ")
            $lineLen = 0
        }
    }
    [void]$sb.AppendLine("`n};")
    [void]$sb.AppendLine("")

    $entries += @{ name = $relPath; arrName = $arrName; size = $size }
}

# 写入资源表
[void]$sb.AppendLine("/* ---- Resource table ---- */")
[void]$sb.AppendLine("const resource_entry_t g_resources[] = {")

foreach ($e in $entries) {
    [void]$sb.AppendLine("  { `"$($e.name)`", $($e.arrName), $($e.size) },")
}

[void]$sb.AppendLine("  { NULL, NULL, 0 }  /* sentinel */")
[void]$sb.AppendLine("};")

# 写入文件
[System.IO.File]::WriteAllText($OutputC, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated $OutputC with $($entries.Count) embedded resources"
