# ================================================================
#  win_port/resource_embed.cmake
#
#  将 resources/ 目录中的文件转换为 C 字节数组并生成
#  resources_embed.c (覆盖 win_port/resource_embed.c 中的
#  空 g_resources 数组).
#
#  用法: cmake -D RESOURCES_DIR=path/to/resources
#              -D OUTPUT_C=path/to/resources_embed.c
#              -P resource_embed.cmake
# ================================================================

if(NOT DEFINED RESOURCES_DIR)
    message(FATAL_ERROR "RESOURCES_DIR not defined")
endif()
if(NOT DEFINED OUTPUT_C)
    message(FATAL_ERROR "OUTPUT_C not defined")
endif()

file(GLOB RESOURCE_FILES "${RESOURCES_DIR}/*")
list(SORT RESOURCE_FILES)

if(NOT RESOURCE_FILES)
    message(WARNING "No resource files found in ${RESOURCES_DIR} — embedding empty array")
endif()

# 生成 .c 文件
file(WRITE "${OUTPUT_C}"
    "/* Auto-generated by CMake — DO NOT EDIT */\n"
    "/* Resource files embedded from: ${RESOURCES_DIR} */\n\n"
    "#include \"resource_embed.h\"\n"
    "#include <stddef.h>\n\n"
)

foreach(RES_FILE ${RESOURCE_FILES})
    get_filename_component(RES_NAME "${RES_FILE}" NAME)

    # 读取二进制内容 → C 字节数组
    file(READ "${RES_FILE}" RES_DATA HEX)
    string(LENGTH "${RES_DATA}" RES_HEX_LEN)

    # 每 2 个十六进制字符 = 1 字节
    math(EXPR RES_SIZE "${RES_HEX_LEN} / 2")

    # 生成数组名 (替换特殊字符为 _)
    string(REGEX REPLACE "[./\\\\ -]" "_" ARRAY_NAME "${RES_NAME}")
    set(ARRAY_NAME "res_${ARRAY_NAME}")

    # 写入数组
    file(APPEND "${OUTPUT_C}"
        "/* ${RES_NAME} — ${RES_SIZE} bytes */\n"
        "static const uint8_t ${ARRAY_NAME}[] = {\n  "
    )

    # 十六进制字符串 → C 字节列表
    set(BYTE_INDEX 0)
    set(LINE_LEN 0)
    while(BYTE_INDEX LESS RES_HEX_LEN)
        string(SUBSTRING "${RES_DATA}" ${BYTE_INDEX} 2 HEX_BYTE)
        file(APPEND "${OUTPUT_C}" "0x${HEX_BYTE}, ")
        math(EXPR LINE_LEN "${LINE_LEN} + 1")
        if(LINE_LEN GREATER_EQUAL 16)
            file(APPEND "${OUTPUT_C}" "\n  ")
            set(LINE_LEN 0)
        endif()
        math(EXPR BYTE_INDEX "${BYTE_INDEX} + 2")
    endwhile()

    file(APPEND "${OUTPUT_C}" "\n};\n\n")
endforeach()

# 写入资源表
file(APPEND "${OUTPUT_C}"
    "/* ---- Resource table ---- */\n"
    "const resource_entry_t g_resources[] = {\n"
)

foreach(RES_FILE ${RESOURCE_FILES})
    get_filename_component(RES_NAME "${RES_FILE}" NAME)
    string(REGEX REPLACE "[./\\\\ -]" "_" ARRAY_NAME "${RES_NAME}")
    file(RELATIVE_PATH RES_PATH "${RESOURCES_DIR}" "${RES_FILE}")

    # 确定子目录: images/ 或 audio/
    get_filename_component(RES_PARENT "${RESOURCES_DIR}" NAME)
    set(VFS_PATH "${RES_NAME}")  # 简化: 直接放在根

    file(APPEND "${OUTPUT_C}"
        "  { \"${VFS_PATH}\", res_${ARRAY_NAME}, sizeof(res_${ARRAY_NAME}) },\n"
    )
endforeach()

file(APPEND "${OUTPUT_C}"
    "  { NULL, NULL, 0 }  /* sentinel */\n"
    "};\n"
)

message(STATUS "Generated ${OUTPUT_C} with embedded resources")
